Upload error log to repo on failure

diff --git a/.github/workflows/build-ios.yml b/.github/workflows/build-ios.yml
--- a/.github/workflows/build-ios.yml
+++ b/.github/workflows/build-ios.yml
@@ -32,12 +32,15 @@ jobs:
           ENTITLEMENTS_REQUIRED="NO" \
           CONFIGURATION_BUILD_DIR=$(pwd)/build > build_log.txt 2>&1 || (cat build_log.txt && exit 1)
 
-    - name: Upload Build Log on Failure
+    - name: Commit Error Log on Failure
       if: failure()
-      uses: actions/upload-artifact@v4
-      with:
-        name: Build-Log
-        path: WlanOptimizerIOS/build_log.txt
+      run: |
+        grep -i "error:" WlanOptimizerIOS/build_log.txt > error_log.txt || true
+        git config --global user.name "github-actions"
+        git config --global user.email "github-actions@github.com"
+        git add error_log.txt
+        git commit -m "Upload error log"
+        git push
 
     - name: Package IPA
       run: |
